[build]
  command = "yarn build"
  publish = "dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://maatester.netlify.app/*"
  to = "https://maatester.com/:splat"
  status = 301
  force = true